### PR TITLE
build on Xcode11 and support swift5

### PR DESCRIPTION
**Pull request by huiping192**

### CODE REVIEW

**Comment by huiping192** [comment]
7326CA68-2787-43C0-96A9-003992A649AF_1_105_c

**Comment by huiping192** [comment]
F281964B-72C2-400D-97F2-0BF654EDBDD0_1_105_c

**Comment by huiping192** [comment]
I make this game playable on the iPhoneX devices. although the background no cover the all screen and the status bar still appear. I don't want make this pull request too large.Planing do the fixs on next pull request.

Thank you!

**Comment by fsiu** [comment]
Thanks!

**Comment by huiping192** [comment]
Thank you for merge the pull request. ^ ^

**Pull request merged**
